[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:xfce]
command=/usr/bin/startxfce4
user=linuxuser
environment=DISPLAY=":1",HOME="/home/linuxuser",USER="linuxuser",LOGNAME="linuxuser",DBUS_SESSION_BUS_ADDRESS="unix:path=/run/dbus/system_bus_socket"
directory=/home/linuxuser
priority=30
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -rfbport 5900 -rfbauth /etc/x11vnc/passwd -forever -shared -localhost -noxdamage -repeat
priority=40
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
priority=50
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
